Separate out push and pr

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -3,6 +3,15 @@ name: Pull Request - Lint and Test Workflow
 on: [pull_request]
 
 jobs:
+  gitflow-enforcer:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check branch
+        if: github.base_ref == 'main' && github.head_ref != 'dev' || github.base_ref == 'production' && github.head_ref != 'main'
+        run: |
+          echo "ERROR: You can only merge to main from dev and to production from main"
+          exit 1
+
   lint:
     runs-on: ubuntu-latest
     steps:
@@ -31,10 +40,15 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
+          role-session-name: "ghgc-backend-github-action"
+          aws-region: "us-west-2"
+
       - name: Launch services
         run: |
-          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
-          AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} \
           docker-compose up --build -d stac raster
 
       - name: Set up Python
@@ -67,6 +81,7 @@ jobs:
 
       - name: Stop services
         run: docker-compose stop
+
   predeploy:
     needs: [test]
 
@@ -84,12 +99,12 @@ jobs:
         with:
           node-version: 17
 
-      - name: Configure awscli
+      - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-west-2
+          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
+          role-session-name: "ghgc-backend-github-action"
+          aws-region: "us-west-2"
 
       - uses: actions/cache@v3
         with:
